### PR TITLE
Fixes order and container screen

### LINKED ISSUE #164: Containers cannot be created anymore.
Login as backoffice id
Go to burger menu & click containers > new container

Add the following parameters
-name
source/destination
link your order. 
Click create. 

Observed:  spinner never goes away. Get Error 422 on the backend. 
Expected: New container creation must work.

### PR DESCRIPTION
**Pull request by harsimranmaan**
Fixes #164 #163

### CODE REVIEW

File: lib/screens/container/add_edit.dart [hunk 1]
```diff
@@ -270,22 +267,17 @@ class _ContainerAddEditState extends State<ContainerAddEdit> {
                 : _reservationTime;
             widget.container.lfd = _lfd == null ? widget.container.lfd : _lfd;
             widget.container.serialNumber = _serialNumber;
-            widget.container.origin = _origin;
-            widget.container.destination = _destination;
+            widget.container.origin = _origin ?? widget.container.origin;
```
Comment (harsimranmaan) [inline lib/screens/container/add_edit.dart:270]: This space a bit more work. There are some edge cases that require handling

**Review by schima — APPROVED** [review]
lgtm
